services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db-test
    volumes:
      - clean-architecture-db-data:/var/lib/mysql
    networks:
      - clean-architecture-network
volumes:
  clean-architecture-db-data:
networks:
  clean-architecture-network:
